# Generated by Django 5.0.3 on 2024-07-07 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="stock_threshold",
            field=models.PositiveIntegerField(default=2),
        ),
    ]
