# Generated by Django 5.0.3 on 2024-07-11 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_product_stock_product_stock_threshold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="initial_stock",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock_threshold",
            field=models.FloatField(default=0.9),
        ),
    ]
